### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by psycki** [exskye/sourcemod#18]
I was looking at some plugins to add to the server, and I came across this plugin, https://forums.alliedmods.net/showthread.php?t=129013
I immediately thought of you, and it would be a great idea to add something similar in your plugin.
in coop version does not think about anything, but in versus mode could be something like, each would control in a different color (in sv 4x4).
also thought in a web panel system to manage the RPG (statistics) and other functions of the plugins / modules, type command via rcon like the HLSW program.
of course are just ideas and very difficult, more is my idea for you ^^
if you need, I am available for testing in the windows ^^

**Comment by exskye** [comment]
I don't actually have much experience with php or web development. I'm not really sure what would go in something like that, to be honest.

In regards to the last boss plugin, in RPG, you can actually upgrade the infected bots talents. Tanks have some pretty devastating talents that I've created in the sample talentmenu.cfg. Talents are completely modular, you just have to play around with it.
